# Generated by Django 2.0.6 on 2018-06-30 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_single_diary_user_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='single_diary',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to='diary.Question_set'),
        ),
        migrations.AlterField(
            model_name='user_answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='diary.Question'),
        ),
    ]
